### ISSUE TITLE
可以提供一个编译好的文件?

### ISSUE THREAD

**Issue by icyfox168168** [bencz/python-jit#1]
谢谢

**Comment by bencz** [comment]
In english please,,,

**Comment by icyfox168168** [comment]
Can you provide a compiled file?

**Comment by bencz** [comment]
Good morning!
unfortunately, I can't put a release here, as it's pretty dependent on the host architecture...
but, you can compile the project... it works ONLY on linux

to compile:

git clone --recursive https://github.com/bencz/python-jit
cd python-jit
mkdir build
cd build
cmake ..

**Comment by icyfox168168** [comment]
I compiled a lot of errors in Windows 11. I originally needed Linux

Thank you for your response
